// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/ccf227b5a84601e2ab3461896603416a410bd212/geojson/geojson.d.ts
declare namespace GeoJSON {
    export type GeoJsonObject = Point | MultiPoint | LineString | MultiLineString | Polygon | MultiPolygon | GeometryCollection | Feature | FeatureCollection;

    /***
    * http://geojson.org/geojson-spec.html#geojson-objects
    */
    export interface GeometryObject {
        bbox?: number[];
        crs?: CoordinateReferenceSystem;
    }

    /***
    * http://geojson.org/geojson-spec.html#positions
    */
    export interface Position {
        [index: number]: number;
    }

    /***
    * http://geojson.org/geojson-spec.html#point
    */
    export interface Point extends GeometryObject {
        type: 'Point';
        coordinates: Position;
    }

    /***
    * http://geojson.org/geojson-spec.html#multipoint
    */
    export interface MultiPoint extends GeometryObject {
        type: 'MultiPoint';
        coordinates: Position[];
    }

    /***
    * http://geojson.org/geojson-spec.html#linestring
    */
    export interface LineString extends GeometryObject {
        type: 'LineString';
        coordinates: Position[];
    }

    /***
    * http://geojson.org/geojson-spec.html#multilinestring
    */
    export interface MultiLineString extends GeometryObject {
        type: 'MultiLineString';
        coordinates: Position[][];
    }

    /***
    * http://geojson.org/geojson-spec.html#polygon
    */
    export interface Polygon extends GeometryObject {
        type: 'Polygon';
        coordinates: Position[][];
    }

    /***
    * http://geojson.org/geojson-spec.html#multipolygon
    */
    export interface MultiPolygon extends GeometryObject {
        type: 'MultiPolygon';
        coordinates: Position[][][];
    }

    /***
    * http://geojson.org/geojson-spec.html#geometry-collection
    */
    export interface GeometryCollection extends GeometryObject {
        type: 'GeometryCollection';
        geometries: GeometryObject[];
    }

    /***
    * http://geojson.org/geojson-spec.html#feature-objects
    */
    export interface Feature extends GeometryObject {
        type: 'Feature'
        geometry: GeoJsonObject;
        properties: any;
        id?: string;
    }

    /***
    * http://geojson.org/geojson-spec.html#feature-collection-objects
    */
    export interface FeatureCollection extends GeometryObject {
        type: 'FeatureCollection'
        features: Feature[];
    }

    /***
    * http://geojson.org/geojson-spec.html#coordinate-reference-system-objects
    */
    export type CoordinateReferenceSystem = NamedCoordinateReferenceSystem | LinkedCoordinateReferenceSystem;

    export interface NamedCoordinateReferenceSystem {
        type: string;
        properties: { name: string }
    }

    export interface LinkedCoordinateReferenceSystem {
        type: string;
        properties: { href: string; type: string }
    }
}
